### ISSUE TITLE
Error with bbdd when starting

### ISSUE THREAD

**Issue by oscarcalvo** [larsbaunwall/bricky#2] opened 2023-02-03 15:22 UTC
When (using Windows) I run docker-compose I get this error "sqlite3.OperationalError: unable to open database file"

![screenshot1](https://user-images.githubusercontent.com/1406535/216639534-ebec4fe3-b694-401e-bf53-0a52909edd17.jpg)

So http://localhost:8080/docs  url doesnt work but the frontend runs, when i write something it throws another error 

![screenshot2](https://user-images.githubusercontent.com/1406535/216640095-2a16051a-bcb9-4780-b1f6-a1011ad11273.jpg)

Any idea? also, if you can provide more info abour the structure of the markdown files and the index, maybe adding a folder with content to the project, would be perfect

thanks

**Comment by larsbaunwall** [comment] 2023-02-03 17:41
Thank you so much for reporting this. Much appreciated! 🤩 

This might be caused by the path for the database store not existing on disk yet. I've made a fix for this case in 8ede5dea83c46e1e786f62885fb96136227f6814.

Also made a folder for the markdown files and will create some samples. For now, any file will do - plain text and markdown alike.

The indexing pipeline will pick up any .md files in the source directory. See this for more info: https://github.com/larsbaunwall/bricky/blob/8ede5dea83c46e1e786f62885fb96136227f6814/api/pipelines/indexing.py#L53

**Comment by larsbaunwall** [comment] 2023-02-06 13:21
Closing this as a bugfix is merged. Feel free to re-open it if it is still an issue.

**Closed by larsbaunwall** 2023-02-06 13:21 UTC
